;pause map tiles for first lava area
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPH, MAP1, MAP1, MAP2, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP1, MAP1, MAPH, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAP1, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP0, MAP0, MAP0, MAP0, MAP1, MAP1, MAP1, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPH, MAP2, MAP2, MAP2, MAP1, MAP1, MAP2, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP1, MAP1, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP1, MAP1, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP1, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPH, MAP0, MAP0, MAP1, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAPH, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
;samus map sprite list
	db ENDLIST
