;pause map tiles for area 2 ruins
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAP0, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP1, MAP0, MAP0, MAP0, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAP0, MAP0, MAP0, MAP3, MAP1, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP0, MAP0, MAP0, MAP0, MAP0, MAP2, MAP2, MAP3, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP0, MAP0, MAP0, MAP2, MAP2, MAP3, MAP1, MAP3, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP0, MAP0, MAP0, MAP1, MAP1, MAP2, MAP2, MAP2, MAP1, MAP1, MAP0, MAP0, MAPH, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP0, MAP0, MAP0, MAP2, MAP0, MAP3, MAP3, MAP3, MAP3, MAP2, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAPH, MAPX, MAPX, MAP2, MAP2, MAP2, MAP2, MAPX, MAPX, MAP2, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP3, MAP3, MAP3, MAP2, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP2, MAP2, MAP2, MAP3, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
;samus map sprite list
	;save and refill
	db AUTOVAL, $00, $38, $40, MAPR, $00
	db AUTOVAL, $00, $58, $50, MAPZ, $00
	db AUTOVAL, $00, $58, $80, MAPZ, $00
	;items
	db VALIDATEBANKD, $30, $40, $60, MAPI, $00	;spring
	db VALIDATEBANKD, $29, $50, $50, MAPI, $00	;varia
	db VALIDATEBANKD, $37, $78, $70, MAPI, $00	;etank
	db VALIDATEBANKD, $35, $78, $80, MAPI, $00	;hijump
	db AUTOVAL, $00, $60, $58, MAPW, $00		;wave
	;missiles
	db VALIDATEBANK9, $26, $40, $48, MAPM, $00
	db VALIDATEBANKD, $2C, $48, $70, MAPM, $00
	db VALIDATEBANKD, $38, $60, $50, MAPM, $00
	db VALIDATEBANKD, $2D, $68, $58, MAPM, $00
	db VALIDATEBANKD, $32, $70, $70, MAPM, $00
	db VALIDATEBANKD, $33, $70, $70, MAPM, $00
	db VALIDATEBANKD, $3B, $78, $68, MAPM, $00
	db VALIDATEBANKD, $34, $78, $70, MAPM, $00
	db ENDLIST
