;pause map tiles for 2nd lava section, areas 4 and 5, and the start of 3rd lava section to the Tower
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAP0, MAP0, MAP2, MAP2, MAP3, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP0, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP1, MAP1, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP2, MAP2, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP3, MAP3, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP2, MAP2, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP3, MAP1, MAP0, MAP1, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP2, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAP3, MAP3, MAP2, MAP2, MAP2, MAP2, MAP0, MAP3, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP2, MAP1, MAP0, MAP0, MAP2, MAP2, MAP2, MAP2, MAP3, MAP3, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP3, MAP3, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAP2, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAPX, MAP1, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAP3, MAP3, MAP2, MAP2, MAP0, MAPX, MAP1, MAP0, MAP0, MAPH, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP0, MAPX, MAPX, MAP0, MAP0, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
;samus map sprite list
	;save and refill
	db AUTOVAL, $00, $58, $58, MAPR, $00
	db AUTOVAL, $00, $58, $60, MAPR, $00
	db AUTOVAL, $00, $80, $48, MAPZ, $00
	;items
	db VALIDATEBANK9, $27, $20, $50, MAPI, $00	;etank
	db VALIDATEBANK9, $20, $30, $50, MAPI, $00	;etank
	db VALIDATEBANKE, $61, $40, $50, MAPI, $00	;screw attack
	db AUTOVAL, $00, $58, $48, MAPW, $00		;plasma
	db AUTOVAL, $00, $60, $48, MAPW, $00	;spazer
	db AUTOVAL, $00, $68, $48, MAPW, $00		;wave
	db AUTOVAL, $00, $70, $48, MAPW, $00		;ice
	;missiles
	db VALIDATEBANK9, $25, $20, $48, MAPM, $00
	db VALIDATEBANKE, $60, $38, $50, MAPM, $00
	db VALIDATEBANK9, $21, $60, $60, MAPM, $00
	db VALIDATEBANK9, $23, $98, $58, MAPM, $00
	db ENDLIST
