;pause map tiles for 2nd lava section, areas 4 and 5, and the start of 3rd lava section to the Tower
	db MAPX, MAPX, MAPX, MAPH, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPV, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAP3, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPH, MAP2, MAP2, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAP3, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAP3, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAP3, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP1, MAP2, MAPX, MAPX
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAPH
	db MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAPX
	db MAPH, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAPX
	db MAPX, MAP2, MAPX, MAPX, MAPX, MAP1, MAP2, MAP2, MAP2, MAP2, MAP2, MAP1, MAPX, MAPX, MAP2, MAP3, MAP3, MAP2, MAP2, MAPX
	db MAPX, MAP2, MAPX, MAPX, MAPX, MAP1, MAP3, MAP3, MAPX, MAPX, MAPX, MAP1, MAP2, MAPX, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAP2, MAPX, MAPX, MAPX, MAPX, MAP3, MAP3, MAP2, MAP2, MAP3, MAP3, MAP2, MAPX, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAP2, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAP2, MAP2, MAPX, MAPX, MAPX, MAPX, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAP3, MAPX, MAPX, MAPX, MAPX, MAP3, MAP2, MAP2, MAP3, MAP3, MAP3, MAP3, MAP2, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAP3, MAPX, MAPX, MAPX, MAPX, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
	db MAPX, MAPX, MAP3, MAP2, MAP2, MAP2, MAP2, MAP3, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX, MAPX
;samus map sprite list
	;save and refill
;	db AUTOVAL, $00, $28, $80, MAPR, $00
;	db AUTOVAL, $00, $38, $78, MAPZ, $00
;	db AUTOVAL, $00, $50, $50, MAPR, $00
	;items
;	db VALIDATEBANKE, $63, $40, $60, MAPI, $00	;space jump
;	db VALIDATEBANKE, $64, $40, $80, MAPI, $00	;etank
;	db AUTOVAL, $00, $50, $60, MAPW, $00	;spazer
;	db VALIDATEBANKE, $6A, $58, $58, MAPI, $00	;etank
;	db AUTOVAL, $00, $60, $58, MAPW, $00		;plasma
	;missiles
;	db VALIDATEBANKE, $6D, $38, $80, MAPM, $00
;	db VALIDATEBANK9, $22, $40, $88, MAPM, $00
;	db VALIDATEBANKE, $6E, $48, $80, MAPM, $00
;	db VALIDATEBANKE, $70, $60, $88, MAPM, $00
	db ENDLIST
