; This file was automatically generated from samus.csv. Please edit that file instead of this one.
pose_standing    = $00 ; Standing
pose_jump        = $01 ; Jumping
pose_spinJump    = $02 ; Spin-jumping
pose_run         = $03 ; Running
pose_crouch      = $04 ; Crouching
pose_morph       = $05 ; Morphball
pose_morphJump   = $06 ; Morphball jumping
pose_fall        = $07 ; Falling
pose_morphFall   = $08 ; Morphball falling
pose_nJumpStart  = $09 ; Starting to jump
pose_spinStart   = $0A ; Starting to spin-jump
pose_spiderRoll  = $0B ; Spider ball rolling
pose_spiderFall  = $0C ; Spider ball falling
pose_spiderJump  = $0D ; Spider ball jumping
pose_spider      = $0E ; Spider ball
pose_hurt        = $0F ; Knockback
pose_morphHurt   = $10 ; Morphball knockback
pose_bombed      = $11 ; Standing bombed
pose_morphBombed = $12 ; Morphball bombed
pose_faceScreen  = $13 ; Facing screen
pose_unusedA     = $14 ; Unused
pose_unusedB     = $15 ; Unused
pose_unusedC     = $16 ; Unused
pose_unusedD     = $17 ; Unused
pose_beingEaten  = $18 ; Being eaten by Metroid Queen
pose_inMouth     = $19 ; In Metroid Queen's mouth
pose_toStomach   = $1A ; Being swallowed by Metroid Queen
pose_inStomach   = $1B ; In Metroid Queen's stomach
pose_outStomach  = $1C ; Escaping Metroid Queen
pose_exitQueen   = $1D ; Escaped Metroid Queen
