; This file was automatically generated from samus.csv. Please edit that file instead of this one.
def pose_standing    = $00 ; Standing
def pose_jump        = $01 ; Jumping
def pose_spinJump    = $02 ; Spin-jumping
def pose_run         = $03 ; Running
def pose_crouch      = $04 ; Crouching
def pose_morph       = $05 ; Morphball
def pose_morphJump   = $06 ; Morphball jumping
def pose_fall        = $07 ; Falling
def pose_morphFall   = $08 ; Morphball falling
def pose_nJumpStart  = $09 ; Starting to jump
def pose_spinStart   = $0A ; Starting to spin-jump
def pose_spiderRoll  = $0B ; Spider ball rolling
def pose_spiderFall  = $0C ; Spider ball falling
def pose_spiderJump  = $0D ; Spider ball jumping
def pose_spider      = $0E ; Spider ball
def pose_hurt        = $0F ; Knockback
def pose_morphHurt   = $10 ; Morphball knockback
def pose_bombed      = $11 ; Standing bombed
def pose_morphBombed = $12 ; Morphball bombed
def pose_faceScreen  = $13 ; Facing screen
def pose_unusedA     = $14 ; Unused
def pose_unusedB     = $15 ; Unused
def pose_unusedC     = $16 ; Unused
def pose_unusedD     = $17 ; Unused
def pose_beingEaten  = $18 ; Being eaten by Metroid Queen
def pose_inMouth     = $19 ; In Metroid Queen's mouth
def pose_toStomach   = $1A ; Being swallowed by Metroid Queen
def pose_inStomach   = $1B ; In Metroid Queen's stomach
def pose_outStomach  = $1C ; Escaping Metroid Queen
def pose_exitQueen   = $1D ; Escaped Metroid Queen
